const fonts = {
  JostBlack: 'Jost-Black',
  JostBlackItalic: 'Jost-BlackItalic',
  JostBold: 'Jost-Bold',
  JostBoldItalic: 'Jost-BoldItalic',
  JostExtraBold: 'Jost-ExtraBold',
  JostExtraBoldItalic: 'Jost-ExtraBoldItalic',
  JostExtraLight: 'Jost-ExtraLight',
  JostExtraLightItalic: 'Jost-ExtraLightItalic',
  JostItalic: 'Jost-Italic',
  JostLight: 'Jost-Light',
  JostLightItalic: 'Jost-LightItalic',
  JostMedium: 'Jost-Medium',
  JostMediumItalic: 'Jost-MediumItalic',
  JostRegular: 'Jost-Regular',
  JostSemiBold: 'Jost-SemiBold',
  JostSemiBoldItalic: 'Jost-SemiBoldItalic',
  JostThin: 'Jost-Thin',
  JostThinItalic: 'Jost-ThinItalic',
  PoppinsBlack: 'Poppins-Black',
  PoppinsBlackItalic: 'Poppins-BlackItalic',
  PoppinsBold: 'Poppins-Bold',
  PoppinsBoldItalic: 'Poppins-BoldItalic',
  PoppinsExtraBold: 'Poppins-ExtraBold',
  PoppinsExtraBoldItalic: 'Poppins-ExtraBoldItalic',
  PoppinsExtraLight: 'Poppins-ExtraLight',
  PoppinsExtraLightItalic: 'Poppins-ExtraLightItalic',
  PoppinsItalic: 'Poppins-Italic',
  PoppinsLight: 'Poppins-Light',
  PoppinsLightItalic: 'Poppins-LightItalic',
  PoppinsMedium: 'Poppins-Medium',
  PoppinsMediumItalic: 'Poppins-MediumItalic',
  PoppinsRegular: 'Poppins-Regular',
  PoppinsSemiBold: 'Poppins-SemiBold',
  PoppinsSemiBoldItalic: 'Poppins-SemiBoldItalic',
  PoppinsThin: 'Poppins-Thin',
  PoppinsThinItalic: 'Poppins-ThinItalic',
};

export default fonts;
