name: Build and Distribute APK to Firebase

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install Dependencies
        run: npm install --global yarn && yarn install

      # Decode Keystore
      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.jks

      # Build APK
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      # Upload to Firebase App Distribution
      - name: Upload to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: fate-app-23e57  # Replace with your Firebase App ID
          token: ${{ secrets.FIREBASE_AUTH_TOKEN }}
          groups: fate-testers
          file: android/app/build/outputs/apk/release/app-release.apk
